### ISSUE TITLE
The plugin is not compatible with Windows

### ISSUE THREAD

**Issue by SleeplessByte** [fathyb/parcel-plugin-typescript#12]
I am assuming the port is in use:

```
{ Error: listen EACCES C:\Users\...\Temp\tmp-90492gfaNZ4bpHiqO
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1487:5)
    at Function.listen (D:\...\node_modules\express\lib\application.js:618:24)
    at new Server (D:\...\node_modules\parcel-plugin-typescript\build\ipc\server.js:27:14)
    at new TypeScriptServer (D:\...\node_modules\parcel-plugin-typescript\build\backend\worker\index.js:28:9)
    at module.exports (D:\...\node_modules\parcel-plugin-typescript\build\index.js:16:24)
    at Bundler.loadPlugins (D:\...\node_modules\parcel-bundler\src\Bundler.js:102:17)
    at <anonymous>
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: 'C:\\Users\\...\\Temp\\tmp-90492gfaNZ4bpHiqO',
```

The plugin errors but the build continues, resulting in paths not being rewritten.

**Comment by fathyb** [comment]
The plugin is not compatible with Windows yet. It's IPC system relies on UNIX sockets, which does not exist in Windows.

I don't have any Windows computer, I'll download a VM and test it.

**Comment by SleeplessByte** [comment]
Right, then I suggest also adding that to the main `README.md` in the meanwhile.

Many tools such as `sidekiq` used to have similar platform-incompatibilities, but I believe that nowadays there are alternatives that work across all platforms. If not as a separate process, can we run the rewrite of paths inline?

**Comment by fathyb** [comment]
I'm going to add this to the `README.md` thanks. The crashing process is the checking process, you only need it to type-check. In the meantime you can [enable the `transpileOnly` option](https://github.com/fathyb/parcel-plugin-typescript#configuration), it'll rewrite the `import` but not type-check.

**Comment by SleeplessByte** [comment]
Just in case the thumbs up was not clear enough and for anyone else stumbling upon this issue: make sure you don't just copy the `transpileOnly` configuration flag from the `README.md`, but also set it to true. This workaround works on Windows!

**Comment by fathyb** [comment]
I published `parcel-plugin-typescript@0.4.2-next.2` to support entirely Windows. If you confirm me it works for you I'll publish it as `0.5.0`.

**Comment by urish** [comment]
`parcel-plugin-typescript@0.4.2-next.2` to did the trick for me, the EACCESS error is now gone :-) 
Thank you!

**Comment by fathyb** [comment]
[`0.5.0` has been released](https://github.com/fathyb/parcel-plugin-typescript/blob/develop/CHANGELOG.md#050-2018-01-14) with this fix amongst others. Thanks to both of you for your feedback!

**Comment by SleeplessByte** [comment]
Thanks man! This has been working for me since 9722f10!
