### ISSUE TITLE
build fails in 0.5.1

### ISSUE THREAD

**Issue by mdurling** [fathyb/parcel-plugin-typescript#14]
```
parcel build ./src/index.html --public-url '/'"

message : Cannot read property 'js' of undefined

🚨  Cannot read property 'js' of undefined
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This problem exists in `0.5.0` and `0.5.1` ... `0.4.1` works fine.

**Comment by fathyb** [comment]
Woops, it's due to the Windows support. I published `parcel-plugin-typescript@0.5.2-next.0` to fix it can you try it?
I created #15 to prevent catch this kind of bugs early.
