### ISSUE TITLE
Import css file to typescript react file

### ISSUE THREAD

**Issue by lednhatkhanh** [fathyb/parcel-plugin-typescript#16]
I tried importing a css file to jsx file with the normal parcel-react setup without any problems but failed to do the same with the .tsx file

**Comment by fathyb** [comment]
Do you have any error message?

**Comment by lednhatkhanh** [comment]
No, I don't see any error message, it just doesn't work

**Comment by fathyb** [comment]
Could you create a reproduction repository? Thanks

**Comment by lednhatkhanh** [comment]
I don't know why but it works now with my repo, gonna close this now, thanks for your time

**Comment by fathyb** [comment]
Great, I think it may be because of the `.cache` directory. I'll add it in the troobleshooting section in the the README and in the issue template.
