### ISSUE TITLE
Code splitting doesn't work for import('modulename')

### ISSUE THREAD

**Issue by subzey** [fathyb/parcel-plugin-typescript#20]
Code splitting doesn't work for `import('modulename')`.

A dynamic import `import('modulename')` in the TS file ultimately becomes
```js
Promise.resolve().then(function(){return require("modulename")})
```
And looks like Parcel doesn't treat it as a [dynamic import](https://parceljs.org/code_splitting.html) merging the `modulename` contents into the entry bundle.

Here's my tsconfig.json:
```json5
{
  "compilerOptions": {
    /* ... Lots of stuff ... */
    "target": "ES5",
    "module": "ESNext"
  }
}
```
And if I compile the TS file with the tsconfig above (`npx tsc`), I have an `import('modulename')` expression in the output JS file (i.e., `import()` stays the same it was).

If I then reference that compiled JS file from the entry HTML, code splitting works fine.

**Comment by subzey** [comment]
I don't know what did really happen, but the very same code is compiled fine today.

Sorry for the inconvenience.

**Comment by fathyb** [comment]
That's fine, thanks for taking the time of reporting it. The plugin should not have any impact on how `import` statement are transpiled. It may have been caused by old data in the `.cache` directory.
