### ISSUE TITLE
Has this plugin to be dependency rather than devDependency?

### ISSUE THREAD

**Issue by shunia** [fathyb/parcel-plugin-typescript#21]
Thanks for this plugin. It's been a long time since I'm seeking `baseUrl` solution from `parcel`, and now I'm back and actually working on this again.

So first question is: Can I install this plugin as a devDependency?

Thanks!

**Comment by fathyb** [comment]
Hey @shunia, yes you can install it in `devDependencies`, in fact I recommend you the `devDependencies` instead of `dependencies` because you don't need any part of the plugin a the runtime.

**Comment by shunia** [comment]
Works great! Thank you.
