### ISSUE TITLE
Source maps do not account for TypeScript source maps, only the transpiled JavaScript

### ISSUE THREAD

**Issue by prencher** [fathyb/parcel-plugin-typescript#25]
Using parcel 1.5.1 and parcel-plugin-typescript 0.5.3, the source maps from TypeScript aren't being picked up, only source maps from the transpiled JavaScript. It works as expected without the plugin.

**Comment by fathyb** [comment]
Fixed in [0.6.0](https://github.com/fathyb/parcel-plugin-typescript/blob/develop/CHANGELOG.md#060-2018-02-11)
