### ISSUE TITLE
Source mapping not working 

### ISSUE THREAD

**Issue by wingland** [fathyb/parcel-plugin-typescript#34]
I found that the source map does not work as the source mapping URL was missing in the generated bundle js file. (map file was not missing)

I later found both in source codes of parcel-bundler and parcel-plugin-typescript, there are codes removing the comment.

https://github.com/fathyb/parcel-plugin-typescript/blob/4d107a673af486f80317390ed7a953668dd77d07/src/frontend/assets/classes/transpile.ts#L56

I opened issue https://github.com/parcel-bundler/parcel/issues/1054 though, and got the response that parcel-plugin-typescript is actually used here. So I opened the same issue here, hoping to get the answer.

Thanks.

**Comment by fathyb** [comment]
Could you provide a minimal reproduction? Thanks.

**Comment by wingland** [comment]
Hi @fathyb , here's my configuration.

package.json
```js
{
  "name": "vue-ts-parcel",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "dev": "rm -rf .cache && rm -rf dist && parcel src/index.html",
    "build": "parcel build src/index.html"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "vue": "^2.5.16",
    "vue-class-component": "^6.2.0",
    "vue-property-decorator": "^6.0.0",
    "vue-template-compiler": "^2.5.16"
  },
  "devDependencies": {
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "parcel-bundler": "^1.6.2",
    "parcel-plugin-typescript": "^0.7.0",
    "parcel-plugin-vue": "^1.5.0",
    "tslint": "^5.9.1",
    "typescript": "^2.6.2",
    "typescript-eslint-parser": "^14.0.0"
  }
}
```
tsconfig.json

```js
{
  "compilerOptions": {
      "module": "es2015",
      "noImplicitAny": true,
      "removeComments": true,
      "moduleResolution": "node",
      "preserveConstEnums": true,
      "sourceMap": true,
      "strict": true,
      "target": "es5",
      "experimentalDecorators": true
  },
  "include": [
      "./src/**/*"
  ],
  "exclude": [
      "node_modules",
      "**/*.spec.ts"
  ],
  "parcelTsPluginOptions": {
    // If true type-checking is disabled
    "transpileOnly": false
  }
}

```

For my full code, it is also available here : https://github.com/wingland/vue-ts-parcel-starter


I wonder why the comment  for "//# sourceMappingURL"  is removed in the parcel-plugin-typescript source code. Is it meant to be added somewhere else?

I did not face the issue when I am not introducing typescript.

**Comment by fathyb** [comment]
The plugin supports source maps, we remove them from module to concatenate into one for the final file. The issue comes from the Vue plugin, if I remove `parcel-plugin-vue` it works.


You can try it yourself :
1. Remove `parcel-plugin-typescript` and it still doesn't work

Or : 

1. Create a `src/test.ts` file, with `console.log('Test source maps')` inside
2. Replace `./index.ts` to `./test.ts`
3. Run `yarn remove parcel-plugin-vue`
4. Run `yarn dev`, you should see `Test source maps` with a reference to the `test.ts` file

**Comment by wingland** [comment]
Thanks @fathyb , I tried and it did work without parcel-plugin-vue, though I need this to resolve vue files. Thanks still. Will check with parcel-plugin-vue.
