### ISSUE TITLE
'transpileOnly' broken for parcel-bundler 1.9.0 and parcel-plugin-typescript 1.0.0

### ISSUE THREAD

**Issue by mjgerace** [fathyb/parcel-plugin-typescript#41]
It seems that the option

```
"parcelTsPluginOptions": {
    // If true type-checking is disabled
    "transpileOnly": false
  }
```

does not work any longer. same setup with previous parcel, and previous parcel-plugin-typescript worked great. Now, I am getting tons of errors output to my console.

**Comment by fathyb** [comment]
What kind of errors are you getting?

Edit: 
[Ah, the config changed](https://github.com/fathyb/parcel-plugin-typescript/blob/develop/CHANGELOG.md#100-2018-06-14) : 
> ### BREAKING CHANGES
>
> * **config:** `parcel-plugin-typescript` should be used instead of `parcelTsPluginOptions` in tsconfig.json

**Comment by mjgerace** [comment]
@fathyb sorry about failure to read that. I know its in the changelog, but changing primary usage docs would be great!
