### ISSUE TITLE
Error when running develop

### ISSUE THREAD

**Issue by mdurling** [fathyb/parcel-plugin-typescript#5]
I get the following error when running `npn run develop`

`
C:\Git\ts-react-parcel>npm run develop

> ts-react-parcel@1.0.0 develop C:\Git\ts-react-parcel
> parcel ./src/index.html

⏳  Building...
Server running at http://localhost:1234
🚨  C:\Git\ts-react-parcel\src\index.tsx: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:207:7)
    at resolve (C:\Git\ts-react-parcel\node_modules\parcel-plugin-typescript\build\backend\transformers\paths.js:28:47)
    at ts.visitEachChild.child (C:\Git\ts-react-parcel\node_modules\parcel-plugin-typescript\build\backend\transformers\paths.js:16:38)
    at visitNodes (C:\Git\ts-react-parcel\node_modules\typescript\lib\typescript.js:51104:48)
    at visitLexicalEnvironment (C:\Git\ts-react-parcel\node_modules\typescript\lib\typescript.js:51137:22)
    at Object.visitEachChild (C:\Git\ts-react-parcel\node_modules\typescript\lib\typescript.js:51431:54)
    at C:\Git\ts-react-parcel\node_modules\parcel-plugin-typescript\build\backend\transformers\paths.js:10:16
    at C:\Git\ts-react-parcel\node_modules\typescript\lib\typescript.js:2601:86
    at reduceLeft (C:\Git\ts-react-parcel\node_modules\typescript\lib\typescript.js:2274:30)
`

**Comment by fathyb** [comment]
Thank you for your feedback, [I've just published 0.2.4](https://github.com/fathyb/parcel-plugin-typescript/blob/develop/CHANGELOG.md) to fix this issue, can you try it?

**Comment by mdurling** [comment]
Thanks. That seems to have resolved the issue, however, I am still struggling to get parcel to resolve dependencies. We use a `./src` baseUrl in our tsconfig so we do things like
```
import { StoreProvider } from 'app/store'
```
Where the module is located in `src/app/store/index.ts`

I get errors like: 
```
/Users/mdurling/Repos/inmotionnow/opus/src/index.tsx(3,31)
Cannot find module 'app/store'.
    2 | import * as ReactDOM from 'react-dom'
  > 3 | import { StoreProvider } from 'app/store'
      |                               ^^^^^^^^^^^
    4 | import { App } from 'app'
```

Any suggestions?

**Comment by fathyb** [comment]
I tried to reproduce it but failed, can you show me your `tsconfig.json`? If you also have a reproduction repository this could help.

**Comment by mdurling** [comment]
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    "baseUrl": "./src",
    "paths": {
      "test/*": [
        "../test/*"
      ],
      "@inmotionnow/react-momentum": [
        "../@inmotionnow/react-momentum"
      ],
      "@inmotionnow/utilities": [
        "../@inmotionnow/utilities"
      ]
    },
    "lib": [
      "es2017",
      "dom"
    ],
    "jsx": "react",
    "noUnusedLocals": true,
    "importHelpers": true
  },
  "exclude": [
    "node_modules",
    "dist"
  ]
}
```
I am trying to convert a rather large repo from webpack to parcel. I can try to create a small repro if this tsconfig doesn't provide any clues.

**Comment by fathyb** [comment]
It seems to work with this `tsconfig.json`, a repro repo might be the only way to figure out why it does not for you. Before you do it can you try to delete the `.cache` folder and relaunch the build? You may have cached files compiled with the older plugin.

**Comment by mdurling** [comment]
I forked [this repo](https://github.com/mdurling/ts-react-parcel) and made some minor changes to recreate the problem. It seems to be related to a) using baseUrl in tsconfig.json and b) defining modules in a folder's `index.ts` file and importing using the folder name.

So, the module is defined in `src/components/app/index.tsx` and imported from `components/app` ... There are no errors reported by VS Code when setting up imports this way.

Thanks for your help!

**Comment by fathyb** [comment]
Thanks for the repo, I found the bug and released `parcel-plugin-typescript@0.2.5-next` to fix it. 
I don't use TypeScript's module resolution yet so it may be flacky, note that the build mode will not work but that will be fixed in the `0.3.0` release in the following days.

If you confirm me you do not encounter any other issues I will release it as `0.2.5`.

**Comment by mdurling** [comment]
I had to remove the `.cache` folder, but after doing so the build was successful in the test repo. I will try it out on our full repo tomorrow. Thanks!

**Comment by llfylwg** [comment]
I can not install this , the error :
error An unexpected error occurred: "http://npm.jd.com/@babel%2fcode-frame: no such package available".
info If you think this is a bug, please open a bug report with the information provided in "D:\\vue-learn\\ts-demo-new\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: http://npm.jd.com/@ngtools%2fwebpack: no such package available
    at Request.params.callback [as _callback] (D:\yarn\lib\cli.js:62098:18)
    at Request.self.callback (D:\yarn\lib\cli.js:123085:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (D:\yarn\lib\cli.js:124068:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (D:\yarn\lib\cli.js:123988:12)
    at Object.onceWrapper (events.js:254:19)

**Comment by fathyb** [comment]
@llfylwg please create a new issue and do not ask help in an unrelated issue. I have created a [new one for you](https://github.com/fathyb/parcel-plugin-typescript/issues/6), please continue the discussion here.

**Comment by mdurling** [comment]
I am still using 0.2.5-next ... I tried upgrading to 0.3.0 today. See separate issue.
