### ISSUE TITLE
Add TSLint output on (re)build

### ISSUE THREAD

**Issue by jaredscheib** [fathyb/parcel-plugin-typescript#51]
Thanks for doing this. Very excited about Parcel and greater TypeScript / ts tooling support!

`TSLing support` is named under "Upcoming features", but in the Project board I don't see a story for this under Ready or In Progress, nor do I see another open or closed issue filed for this here.

Getting TSlint output during rebuilds with Webpack is an instrumental part of my development flow, and for my team's. We're wanting to switch over to Parcel but not having TSLint support/output is a blocker. Any insight into when this might be coming? We're might be willing to tackle it as an outisde contribution, but wanted to check in on the status first.

Thanks!

**Comment by fathyb** [comment]
Hey, I almost stopped using the plugin (and TypeScript ☹️) when switching company a month ago, this is why the development slowed down. I began working a bit on the linter support but it's not complete (especially the reporting part): https://github.com/fathyb/parcel-plugin-typescript/blob/516bb2a79a45c39fb5c12233a9e654a31dde9d56/src/backend/linter/index.ts#L1-L35

I might start working back on this this week-end as implementing this may fix other issues with the plugin (mainly duplicates errors/better reporting), and I really start to miss ts. I'll update this issue Sunday, and contributions are more than welcome!

**Comment by jaredscheib** [comment]
Hey @fathyb, thanks so much for your thoughtful response. After a lot more research in the past couple of days, I came to believe that the build process is not the place for linting & type-checking. Instead, I think lint and type errors are better guarded against at the continuous integration point, and so for our project we instead added new scripts to make it easy to lint (`eslint`, `tslint`) and type-check (`tsc`): https://github.com/influxdata/chronograf/pull/3845. And then to fail the build at the CI point if any of those fail: https://github.com/influxdata/chronograf/pull/4001.

See my comments on those PRs and at https://github.com/parcel-bundler/parcel/issues/953 for more context.

So I retract my request, and at any rate, thank you again! :)
