### ISSUE TITLE
how to use "absolute" paths from a baseUrl for imports?

### ISSUE THREAD

**Issue by raould** [fathyb/parcel-plugin-typescript#53]
hi, I don't want my imports to have "./foo.ts" or "../../bar/bar.ts" in them. I want them to be like "src/foo.ts" and "src/bar/bar.ts" or some such. Point being they should all be absolute from some root, and that root is I guess usually the baseUrl maybe in tsconfig.json?

I guess this is all https://github.com/parcel-bundler/parcel/issues/202

Anyway, how do I get this to work with this plugin? Do I have to somehow extract the tsconfig.json from parcel, and then manually edit it, and keep it around explicitly in my project?

When I make one tho I think [I am running into the "!! Unexpected token }" issue](https://github.com/fathyb/parcel-plugin-typescript/issues/45) so I feel a tad confused and stuck.

**Comment by fathyb** [comment]
Just use `paths` and `baseUrl` in your `tsconfig.json`
