### ISSUE TITLE
Errors are detected only when file is changed.

### ISSUE THREAD

**Issue by lxzxl** [fathyb/parcel-plugin-typescript#8]
I have a tsx file with error, but when I run `parcel index.html`, there is no error message. Only when I modified that file, the error is detected and displayed. Does anyone have same problem?

I'm using `parcel-plugin-typescript@0.2.5`

**Comment by fathyb** [comment]
This may be because of Parcel's cache. If you remove the `.cache` directory before building does it show the error?

**Comment by lxzxl** [comment]
@fathyb You are correct, the cache causes the problem.

**Comment by fathyb** [comment]
The `noEmitError` TypeScript option [is now supported](https://github.com/fathyb/parcel-plugin-typescript/blob/develop/CHANGELOG.md#050-2018-01-14). If enabled the plugin will not write in the cache if the file has an error. It resolves this issue when enabled.

Feel free to reopen if needed.
