### ISSUE TITLE
Don't emit javascript on type error

### ISSUE THREAD

**Issue by danr** [fathyb/parcel-plugin-typescript#9]
Is it possible for this plugin to make it so that the module is not hot-reloaded in the presence of type errors? Right now this plugin shows you the error in the terminal, but the javascript is sent to the browser regardless.

**Comment by fathyb** [comment]
Yes we can, will doing this when `compilerOptions.noEmitOnError` is set to `true` is good for you?

**Comment by danr** [comment]
Yes, that sounds excellent!

**Comment by danr** [comment]
Ideally the error should also be written it the developer console when using hot module reloading.

**Comment by fathyb** [comment]
I opened #10 for displaying the errors in the console, will ping you here with a prelease when it's done.

**Comment by fathyb** [comment]
@danr `parcel-plugin-typescript@0.5.0-next.0` has been released with this feature, you need to set `noEmitError` on your `compilerOptions` to true.

**Comment by danr** [comment]
Thanks! My initial tests indicate that it works like a charm. :tada:
